<?php
/**@var  Amasty\UserName\Block\Index $block */

?>

<div>
    <form action="<?=  $block->getUrl('*/cart/add'); ?>">
        <div  class="<?= $this->getData('class_form'); ?>">
            <label for="sku">sku</label>
            <input type="text" id="sku" name="sku" size="20" ></Br>
            <?= ($block->showQty()=='1') ? '<label for="qty">qty</label></Br><input type="number" id="qty" value="'.$block->getDefaultValueQty().'" name="qty" size="20">' : '' ?>
        </div>

        <div class="<?= $this->getData('class_additional'); ?>">
            <?= $block->getChildHtml(); ?>
        </div>

        <div align="right">
            <button>Отправить</button>
        </div>
    </form>
</div>
