<div>
    <form action="\">
        <div  class="<?= $this->getData('class_form'); ?>">
            <label for="sku">sku</label>
            <input type="text" name="sku" size="20"></Br>
            <label for="qty">qty</label></Br>
            <input type="number" name="qty" size="20">
        </div>

        <div class="<?= $this->getData('class_additional'); ?>">
            <?= $block->getChildHtml(); ?>
        </div>

        <div align="right">
            <button>Отправить</button>
        </div>
    </form>
</div>
